project_id = "jnqivntlkemzcpomkvwv"

[functions.sync-shopify-metrics]
verify_jwt = false

[functions.store-platform-connection]
verify_jwt = false

[functions.sync-meta-metrics]
verify_jwt = false

[functions.meta-oauth-callback]
verify_jwt = false

[functions.create-client-user]
verify_jwt = false

[functions.shopify-oauth-callback]
verify_jwt = false

[functions.google-ads-oauth-callback]
verify_jwt = false

[functions.sync-google-ads-metrics]
verify_jwt = false

[functions.steve-chat]
verify_jwt = false
